# Ray Unit 3 - Sharded Data

Pandas puts an entire DF in RAM. What if the data is too big?

Ray shards the data into blocks while keeping a pandas-like API.

Popular alternatives: Spark, Dask, Daft.

## Setup

Use the same `22971-ray` environment and notebook kernel as the previous units.

In [17]:
import math
import time
from pathlib import Path

import numpy as np
import pandas as pd
import ray
from IPython.display import display
from ray.data.aggregate import AggregateFnV2, Count, Mean, Sum
from ray.data.block import BlockAccessor

ray.shutdown()
ray.init(
    ignore_reinit_error=True,
    include_dashboard=False,
    log_to_driver=False,
    logging_level='ERROR',
)
print('Ray version:', ray.__version__)
print('Ray resources:', ray.cluster_resources())

Ray version: 2.54.0
Ray resources: {'object_store_memory': 4911500083.0, 'GPU': 1.0, 'memory': 11460166861.0, 'node:__internal_head__': 1.0, 'accelerator_type:G': 1.0, 'node:127.0.0.1': 1.0, 'CPU': 12.0}

## 0. Generate data

We generate synthetic gameplay telemetry data with these columns:

    | Column | Type |
    |---|---|
    | `event_ts` | `timestamp[ns]` |
    | `player_id` | `int32` |
    | `session_id` | `int32` |
    | `region` | `string` |
    | `platform` | `string` |
    | `event_type` | `string` |
    | `level_id` | `int16` |
    | `latency_ms` | `int32` |
    | `spend_usd` | `float` |
    | `is_test_user` | `bool` |
    | `payload_blob` | `string` |

- `payload_blob` is a long nonsense string that makes each row artificially wide.
- We save the dataset to `...\fake_data\part-XX.parquet`.
- The dataset is split into `NUM_SHARDS` parquet shards.

### Helper functions

In [18]:
SEED = 0
N_ROWS = 60_000
NUM_SHARDS = 8
PAYLOAD_CHARS = 2_000 #2 KB per row
DATA_DIR = 'fake_data'
OUT_DIR = 'output'

REGIONS = np.array(['NA', 'EU', 'APAC', 'LATAM', 'MEA'])
PLATFORMS = np.array(['pc', 'console', 'mobile'])
EVENT_TYPES = np.array(['match_start', 'match_end', 'quest', 'purchase', 'crash', 'chat'])


def build_payload_column(n_rows, payload_chars=PAYLOAD_CHARS):
    seeds = pd.Series(np.arange(n_rows), dtype='int64').map(
        lambda i: f'blob-{i:07d}-{(i * 2654435761) & 0xFFFFFFFF:08x}'
    )
    return seeds.str.pad(payload_chars, side='right', fillchar='x')


def build_telemetry_frame(n_rows=N_ROWS, seed=SEED, payload_chars=PAYLOAD_CHARS):
    rng = np.random.default_rng(seed)
    event_type = rng.choice(EVENT_TYPES, size=n_rows, p=[0.28, 0.22, 0.25, 0.07, 0.03, 0.15])
    event_ts = pd.Timestamp('2025-01-01') + pd.to_timedelta(
        rng.integers(0, 14 * 24 * 60 * 60, size=n_rows),
        unit='s',
    )
    latency_ms = np.round(
        rng.gamma(shape=2.4, scale=32.0, size=n_rows) + rng.integers(5, 25, size=n_rows)
    ).astype('int32')
    latency_ms[event_type == 'crash'] *= 2

    spend_usd = np.zeros(n_rows, dtype='float32')
    purchase_mask = event_type == 'purchase'
    spend_usd[purchase_mask] = rng.uniform(0.99, 59.99, size=purchase_mask.sum()).round(2)

    frame = pd.DataFrame(
        {
            'event_ts': event_ts,
            'player_id': rng.integers(10_000, 90_000, size=n_rows, dtype=np.int32),
            'session_id': rng.integers(100_000, 900_000, size=n_rows, dtype=np.int32),
            'region': rng.choice(REGIONS, size=n_rows, p=[0.36, 0.27, 0.22, 0.10, 0.05]),
            'platform': rng.choice(PLATFORMS, size=n_rows, p=[0.42, 0.18, 0.40]),
            'event_type': event_type,
            'level_id': rng.integers(1, 60, size=n_rows, dtype=np.int16),
            'latency_ms': latency_ms,
            'spend_usd': spend_usd,
            'is_test_user': rng.random(n_rows) < 0.02,
            'payload_blob': build_payload_column(n_rows, payload_chars),
        }
    )

    return frame.reset_index(drop=True)


def write_parquet_shards(frame, out_dir, num_shards=NUM_SHARDS):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rows_per_shard = math.ceil(len(frame) / num_shards)
    for shard_id in range(num_shards):
        start = shard_id * rows_per_shard
        stop = min((shard_id + 1) * rows_per_shard, len(frame))
        shard = frame.iloc[start:stop]
        if shard.empty:
            continue
        shard.to_parquet(out_dir / f'part-{shard_id:02d}.parquet', index=False)


def enrich_batch(batch):
    batch = batch.copy()
    batch['hour_of_day'] = batch['event_ts'].dt.hour.astype('int8')
    batch['is_purchase'] = batch['event_type'].eq('purchase')
    batch['is_crash'] = batch['event_type'].eq('crash')
    batch['latency_band'] = pd.cut(
        batch['latency_ms'],
        bins=[-1, 60, 120, 240, np.inf],
        labels=['fast', 'stable', 'slow', 'spiky'],
    ).astype('string')
    return batch

### Data generation

In [19]:
workspace_dir = Path.cwd()  
input_dir = workspace_dir / DATA_DIR
output_dir = workspace_dir / OUT_DIR

workspace_dir.mkdir(parents=True, exist_ok=True)

existing_shards = sorted(input_dir.glob('part-*.parquet'))
if existing_shards:
    print(f"Found {len(existing_shards)} existing parquet shards in {input_dir}; skipping generation.")
    telemetry_pdf = pd.concat((pd.read_parquet(path) for path in existing_shards), ignore_index=True)
else:
    telemetry_pdf = build_telemetry_frame()
    write_parquet_shards(telemetry_pdf, input_dir, num_shards=NUM_SHARDS)

display(telemetry_pdf.head())
size_bytes = telemetry_pdf.memory_usage(deep=True).sum()
print(f"size: {size_bytes / 1024**2:.2f} MiB")

Found 8 existing parquet shards in c:\Users\alter\OneDrive\Documents\GitHub\OU-22971-Toolbox\Ray\3_ray_data\fake_data; skipping generation.

,event_ts,player_id,session_id,region,platform,event_type,level_id,latency_ms,spend_usd,is_test_user,payload_blob
0,2025-01-05 04:02:26,81408,502575,APAC,pc,quest,49,53,0.00,False,blob-0000000-00000000xxxxxxxxxxxxxxxxxxxxxxxxx...
1,2025-01-10 17:00:11,60826,556316,APAC,console,match_start,44,129,0.00,False,blob-0000001-9e3779b1xxxxxxxxxxxxxxxxxxxxxxxxx...
2,2025-01-07 21:20:43,82367,334510,EU,pc,match_start,20,100,0.00,False,blob-0000002-3c6ef362xxxxxxxxxxxxxxxxxxxxxxxxx...
3,2025-01-03 19:40:54,41559,168491,EU,pc,match_start,1,143,0.00,False,blob-0000003-daa66d13xxxxxxxxxxxxxxxxxxxxxxxxx...
4,2025-01-14 06:36:17,59378,497715,EU,mobile,purchase,7,133,2.09,False,blob-0000004-78dde6c4xxxxxxxxxxxxxxxxxxxxxxxxx...

size: 128.05 MiB

## 1. Ray Data mental model

#### A Ray `Dataset` feels a lot like a pandas `DataFrame` for the operations in this notebook.

In [20]:
events_ds = ray.data.read_parquet(str(input_dir), override_num_blocks=NUM_SHARDS)

Parquet dataset sampling: 100%|██████████| 2.00/2.00 [00:00<00:00, 2.08 file/s]
2026-05-14 13:10:41,711	INFO parquet_datasource.py:1079 -- Estimated parquet encoding ratio is 14.810.
2026-05-14 13:10:41,711	INFO parquet_datasource.py:1139 -- Estimated parquet reader batch size at 65218 rows

In [21]:
events_ds.show(5)

2026-05-14 13:10:42,544	INFO logging.py:392 -- Registered dataset logger for dataset dataset_1_0
2026-05-14 13:10:42,547	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_1_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:42,547	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_1_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> LimitOperator[limit=5]
2026-05-14 13:10:43,494	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_1_0 =======
2026-05-14 13:10:43,497	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:43,497	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:43,498	INFO logging_progress.py:181 --
2026-05-14 13:10:43,498	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:43,499	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:43,499	INFO logging_progress.py:231 -- limit=5: 0/1
2026-05-14 13:10:43,500	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store
2026-05-14 13:10:43,501	INFO logging_progress.py:192 -- ============================================
2026-05-14 13:10:43,975	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_1_0 execution finished in 1.43 seconds

{'event_ts': Timestamp('2025-01-05 04:02:26'), 'player_id': 81408, 'session_id': 502575, 'region': 'APAC', 'platform': 'pc', 'event_type': 'quest', 'level_id': 49, 'latency_ms': 53, 'spend_usd': 0.0, 'is_test_user': False, 'payload_blob': 'blob-0000000-00000000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
{'event_ts': Timestamp('2025-01-10 17:00:11'), 'player_id': 60826, 'session_id': 556316, 'region': 'APAC', 'platform': 'console', 'event_type': 'match_start', 'level_id': 44, 'latency_ms': 129, 'spend_usd': 0.0, 'is_test_user': False, 'payload_blob': 'blob-0000001-9e3779b1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
{'event_ts': Timestamp('2025-01-07 21:20:43'), 'player_id': 82367, 'session_id': 334510, 'region': 'EU', 'platform': 'pc', 'event_type': 'match_start', 'level_id': 20, 'latency_ms': 100, 'spend_usd': 0.0, 'is_test_user': False, 'payload_blob': 'blob-0000002-3c6ef362xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
{'event_ts': Timestamp('2025-01-03 19:40:54'), 'player_id': 41559, 'session_id': 168491, 'region': 'EU', 'platform': 'pc', 'event_type': 'match_start', 'level_id': 1, 'latency_ms': 143, 'spend_usd': 0.0, 'is_test_user': False, 'payload_blob': 'blob-0000003-daa66d13xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
{'event_ts': Timestamp('2025-01-14 06:36:17'), 'player_id': 59378, 'session_id': 497715, 'region': 'EU', 'platform': 'mobile', 'event_type': 'purchase', 'level_id': 7, 'latency_ms': 133, 'spend_usd': 2.0899999141693115, 'is_test_user': False, 'payload_blob': 'blob-0000004-78dde6c4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}

#### The dataset is sharded into **blocks**: each block is stored as a separate object in Ray's object store.

![blocks.png](images/blocks.png)

Source: [Ray docs](https://docs.ray.io/en/latest/data/key-concepts.html)

In [22]:
# We don't need to know what ref_bundles are (ray.data internals)
for bundle_idx, ref_bundle in enumerate(events_ds.iter_internal_ref_bundles()):
    [(block_ref, metadata)] = ref_bundle.blocks
    print(f"block {bundle_idx}: ref={block_ref}, rows={metadata.num_rows}, size={metadata.size_bytes / 1024**2:.2f} MiB")

2026-05-14 13:10:43,993	INFO logging.py:392 -- Registered dataset logger for dataset dataset_0_0
2026-05-14 13:10:43,997	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_0_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:44,001	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_0_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet]
2026-05-14 13:10:44,027	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_0_0 =======
2026-05-14 13:10:44,029	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:44,029	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:44,031	INFO logging_progress.py:181 --
2026-05-14 13:10:44,032	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:44,033	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:44,033	INFO logging_progress.py:192 -- ============================================

block 0: ref=ObjectRef(8ae36a0c2e08d5aeffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 1: ref=ObjectRef(15b74098d9f345eaffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 2: ref=ObjectRef(342a1b2e7481ecd0ffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 3: ref=ObjectRef(e8d83d0432dffd50ffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB

2026-05-14 13:10:46,016	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_0_0 execution finished in 2.02 seconds

block 4: ref=ObjectRef(cbe2816dc916ea0bffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 5: ref=ObjectRef(de539dc9a5d0424fffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 6: ref=ObjectRef(20e9f4113ef956bbffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB
block 7: ref=ObjectRef(462cc66bb1db4c70ffffffffffffffffffffffff0100000002000000), rows=7500, size=14.72 MiB

#### Execution is **lazy**: no data is manipulated unless explicitly required.

In [23]:
sorted_ds = events_ds.sort(key='event_ts')

Why did this cell run instantly?

Ray Data built a plan:

1. Read the data from the source files, with different tasks reading different blocks.
2. Sort the rows by `event_ts`.

**It did not execute that plan yet.**

In [24]:
sorted_ds.explain()

-------- Logical Plan --------
Sort[Sort]
+- Read[ReadParquet]

-------- Logical Plan (Optimized) --------
Sort[Sort]
+- Read[ReadParquet]

-------- Physical Plan --------
AllToAllOperator[Sort]
+- TaskPoolMapOperator[ReadParquet]
   +- InputDataBuffer[Input]

-------- Physical Plan (Optimized) --------
AllToAllOperator[Sort]
+- TaskPoolMapOperator[ReadParquet]
   +- InputDataBuffer[Input]

We can tell Ray to execute the plan explicitly.

In [25]:
events_materialized = sorted_ds.materialize()

2026-05-14 13:10:46,048	INFO logging.py:392 -- Registered dataset logger for dataset dataset_3_0
2026-05-14 13:10:46,053	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_3_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:46,054	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_3_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> AllToAllOperator[Sort]
2026-05-14 13:10:46,074	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_3_0 =======
2026-05-14 13:10:46,077	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:46,077	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:46,079	INFO logging_progress.py:181 --
2026-05-14 13:10:46,079	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:46,080	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:46,081	INFO logging_progress.py:231 -- Sort: 0/1
2026-05-14 13:10:46,081	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store; 0 rows output
2026-05-14 13:10:46,082	INFO logging_progress.py:231 --     - Sort Sample: 0/1
2026-05-14 13:10:46,083	INFO logging_progress.py:231 --     - Shuffle Map: 0/1
2026-05-14 13:10:46,084	INFO logging_progress.py:231 --     - Shuffle Reduce: 0/1
2026-05-14 13:10:46,085	INFO logging_progress.py:192 -- ============================================
2026-05-14 13:10:46,467	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_3_0 execution finished in 0.41 seconds

- Some methods trigger execution (e.g. `show()`, `sum()`, `materialize()`).
- Some methods are lazy (e.g. `sort()`, `groupby()`, `groupby(...).aggregate()`).

If a method returns another `Dataset` or `GroupedData`, it is usually still lazy.

**Common footgun**: triggering execution unintentionally can dominate runtime.

## 2. Cheap vs expensive operations

In pandas, these often feel interchangeable:

```
df.methodA.methodB
df.methodB.methodA
```

With distributed data, the shape of the final execution plan matters much more.

**Important nuance:** Until the dataset is consumed or materialized, Ray is building a logical plan, optimizing it, and then lowering it to a physical plan, which makes two lazy, block-local calls effectively interchangeable (usually).

![plan optimizer.png](images/plan_optimizer.png)

Source: [Ray docs](https://docs.ray.io/en/latest/data/key-concepts.html#operators-and-plans)

### Example: wide vs narrow sort

**Goal:** sort by `event_ts` and end with the same narrow columns, without `payload_blob`.

#### Option 1: sort wide, then drop `payload_blob`

In [26]:
narrow_columns = [name for name in events_ds.schema().names if name != 'payload_blob']

wide_events = ray.data.read_parquet(str(input_dir), override_num_blocks=NUM_SHARDS)
start = time.perf_counter()

# This materialize() is an optimization boundary:
# Ray must execute the wide sort now, with payload_blob still present.
wide_sorted_with_blob = wide_events.sort('event_ts').materialize()

wide_sorted = wide_sorted_with_blob.select_columns(narrow_columns)
wide_elapsed = time.perf_counter() - start

Parquet dataset sampling: 100%|██████████| 2.00/2.00 [00:00<00:00, 92.8 file/s]
2026-05-14 13:10:46,527	INFO parquet_datasource.py:1079 -- Estimated parquet encoding ratio is 14.810.
2026-05-14 13:10:46,527	INFO parquet_datasource.py:1139 -- Estimated parquet reader batch size at 65218 rows
2026-05-14 13:10:46,534	INFO logging.py:392 -- Registered dataset logger for dataset dataset_7_0
2026-05-14 13:10:46,537	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_7_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:46,538	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_7_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> AllToAllOperator[Sort]
2026-05-14 13:10:46,561	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_7_0 =======
2026-05-14 13:10:46,564	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:46,565	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:46,565	INFO logging_progress.py:181 --
2026-05-14 13:10:46,565	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:46,566	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:46,567	INFO logging_progress.py:231 -- Sort: 0/1
2026-05-14 13:10:46,568	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store; 0 rows output
2026-05-14 13:10:46,568	INFO logging_progress.py:231 --     - Sort Sample: 0/1
2026-05-14 13:10:46,569	INFO logging_progress.py:231 --     - Shuffle Map: 0/1
2026-05-14 13:10:46,570	INFO logging_progress.py:231 --     - Shuffle Reduce: 0/1
2026-05-14 13:10:46,570	INFO logging_progress.py:192 -- ============================================
2026-05-14 13:10:46,949	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_7_0 execution finished in 0.41 seconds

#### Option 2: drop `payload_blob` first

In [27]:

narrow_events = ray.data.read_parquet(str(input_dir), override_num_blocks=NUM_SHARDS)
start = time.perf_counter()
narrow_sorted = (
    narrow_events
    .select_columns(narrow_columns)
    .sort('event_ts')
    .materialize()
)
narrow_elapsed = time.perf_counter() - start

print(f'wide sort elapsed: {wide_elapsed:.2f} s')
print(f'narrow sort elapsed: {narrow_elapsed:.2f} s')
print(f'wide / narrow ratio: {wide_elapsed / narrow_elapsed:.2f}x')

Parquet dataset sampling: 100%|██████████| 2.00/2.00 [00:00<00:00, 105 file/s]
2026-05-14 13:10:47,002	INFO parquet_datasource.py:1079 -- Estimated parquet encoding ratio is 14.810.
2026-05-14 13:10:47,002	INFO parquet_datasource.py:1139 -- Estimated parquet reader batch size at 65218 rows
2026-05-14 13:10:47,008	INFO logging.py:392 -- Registered dataset logger for dataset dataset_13_0
2026-05-14 13:10:47,012	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_13_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:47,013	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_13_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> AllToAllOperator[Sort]
2026-05-14 13:10:47,036	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_13_0 =======
2026-05-14 13:10:47,039	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:47,039	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:47,039	INFO logging_progress.py:181 --
2026-05-14 13:10:47,041	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:47,042	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:47,042	INFO logging_progress.py:231 -- Sort: 0/1
2026-05-14 13:10:47,043	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.0 CPU, 0.0B object store; 0 rows output
2026-05-14 13:10:47,044	INFO logging_progress.py:231 --     - Sort Sample: 0/1
2026-05-14 13:10:47,044	INFO logging_progress.py:231 --     - Shuffle Map: 0/1
2026-05-14 13:10:47,045	INFO logging_progress.py:231 --     - Shuffle Reduce: 0/1
2026-05-14 13:10:47,049	INFO logging_progress.py:192 -- =============================================
2026-05-14 13:10:47,149	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_13_0 execution finished in 0.14 seconds

wide sort elapsed: 0.44 s
narrow sort elapsed: 0.16 s
wide / narrow ratio: 2.71x

In [28]:
# Run stats before any preview action like show() or take().
# Those actions record their own limit/iteration work in the dataset stats.
print(wide_sorted_with_blob.stats())
print('\n'+ '='*20+'\n')
print(narrow_sorted.stats())

Operator 1 ReadParquet: 8 tasks executed, 8 blocks produced in 0.07s
* Remote wall time: 14.19ms min, 40.27ms max, 30.63ms mean, 245.07ms total
* Remote cpu time: 15.62ms min, 46.88ms max, 29.3ms mean, 234.38ms total
* UDF time: 0us min, 0us max, 0.0us mean, 0us total
* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
* Output num rows per block: 7500 min, 7500 max, 7500 mean, 60000 total
* Output size bytes per block: 15431929 min, 15432845 max, 15432487 mean, 123459900 total
* Output rows per task: 7500 min, 7500 max, 7500 mean, 8 tasks used
* Tasks per node: 8 min, 8 max, 8 mean; 1 nodes used
* Operator throughput:
	* Total input num rows: 0 rows
	* Total output num rows: 60000 rows
	* Ray Data throughput: 804031.9522297174 rows/s
	* Estimated single task throughput: 244831.0053877847 rows/s

Operator 2 Sort: executed in 0.41s

	Suboperator 0 SortMap: 1 tasks executed, 8 blocks produced
	* Remote wall time: 7.38ms min, 27.99ms max, 21.06ms mean, 168.49ms total
	* Remote cpu time: 15.62ms min, 31.25ms max, 19.53ms mean, 156.25ms total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 7500 min, 7500 max, 7500 mean, 60000 total
	* Output size bytes per block: 15427239 min, 15428155 max, 15427797 mean, 123422380 total
	* Output rows per task: 60000 min, 60000 max, 60000 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 60000 rows
		* Total output num rows: 60000 rows
		* Ray Data throughput: 1816651.427573008 rows/s
		* Estimated single task throughput: 356110.9832340908 rows/s

	Suboperator 1 SortReduce: 1 tasks executed, 8 blocks produced
	* Remote wall time: 30.87ms min, 60.69ms max, 38.98ms mean, 311.86ms total
	* Remote cpu time: 15.62ms min, 62.5ms max, 33.2ms mean, 265.62ms total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 6204 min, 8815 max, 7500 mean, 60000 total
	* Output size bytes per block: 12765169 min, 18137369 max, 15431548 mean, 123452391 total
	* Output rows per task: 60000 min, 60000 max, 60000 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 60000 rows
		* Total output num rows: 60000 rows
		* Ray Data throughput: 988607.9412470085 rows/s
		* Estimated single task throughput: 192396.12051266807 rows/s

Dataset throughput:
	* Ray Data throughput: 167990.29016258617 rows/s


====================

Operator 1 ReadParquet: 8 tasks executed, 8 blocks produced in 0.04s
* Remote wall time: 3.81ms min, 11.69ms max, 6.63ms mean, 53.06ms total
* Remote cpu time: 0.0us min, 15.62ms max, 5.86ms mean, 46.88ms total
* UDF time: 0us min, 0us max, 0.0us mean, 0us total
* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
* Output num rows per block: 7500 min, 7500 max, 7500 mean, 60000 total
* Output size bytes per block: 401929 min, 402845 max, 402487 mean, 3219900 total
* Output rows per task: 7500 min, 7500 max, 7500 mean, 8 tasks used
* Tasks per node: 8 min, 8 max, 8 mean; 1 nodes used
* Operator throughput:
	* Total input num rows: 0 rows
	* Total output num rows: 60000 rows
	* Ray Data throughput: 1643867.1421530638 rows/s
	* Estimated single task throughput: 1130840.08216014 rows/s

Operator 2 Sort: executed in 0.14s

	Suboperator 0 SortMap: 1 tasks executed, 8 blocks produced
	* Remote wall time: 1.68ms min, 1.94ms max, 1.79ms mean, 14.3ms total
	* Remote cpu time: 0.0us min, 0.0us max, 0.0us mean, 0.0us total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 7500 min, 7500 max, 7500 mean, 60000 total
	* Output size bytes per block: 397239 min, 398155 max, 397797 mean, 3182380 total
	* Output rows per task: 60000 min, 60000 max, 60000 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 60000 rows
		* Total output num rows: 60000 rows
		* Ray Data throughput: 9277155.02229008 rows/s
		* Estimated single task throughput: 4194484.261613566 rows/s

	Suboperator 1 SortReduce: 1 tasks executed, 8 blocks produced
	* Remote wall time: 2.02ms min, 3.55ms max, 2.65ms mean, 21.19ms total
	* Remote cpu time: 0.0us min, 0.0us max, 0.0us mean, 0.0us total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 4986 min, 11924 max, 7500 mean, 60000 total
	* Output size bytes per block: 266873 min, 637318 max, 400612 mean, 3204896 total
	* Output rows per task: 60000 min, 60000 max, 60000 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 60000 rows
		* Total output num rows: 60000 rows
		* Ray Data throughput: 14918322.15820732 rows/s
		* Estimated single task throughput: 2831911.8680887 rows/s

Dataset throughput:
	* Ray Data throughput: 617373.5078037982 rows/s

#### Reading the `stats()` output

- `ReadParquet` -> `Output size bytes`: did Ray read the wide payload column or only the projected columns?
- `Sort` -> `executed in ...`: how long did the global sort stage take?
- `SortMap` / `SortReduce` -> `Output size bytes`: how much data moved through the sort?

### Global aggregation is expensive

This is not another method-order example. The first run is a projection-only baseline. The second run uses the same projection, then adds `groupby(...).aggregate(...)`.

The outputs are intentionally different; compare the timings and stats only to isolate the extra cost of global aggregation.

In [29]:
local_events = ray.data.read_parquet(str(input_dir), override_num_blocks=NUM_SHARDS)
start = time.perf_counter()
local_projected = (
    local_events
    .select_columns(['region', 'latency_ms', 'spend_usd'])
    .materialize()
)
local_elapsed = time.perf_counter() - start

grouped_events = ray.data.read_parquet(str(input_dir), override_num_blocks=NUM_SHARDS)
start = time.perf_counter()
region_summary = (
    grouped_events
    .select_columns(['region', 'latency_ms', 'spend_usd'])
    .groupby('region')
    .aggregate(
        Count(alias_name='events'),
        Mean('latency_ms', alias_name='mean_latency_ms'),
        Sum('spend_usd', alias_name='total_spend_usd'),
    )
    .materialize()
)
grouped_elapsed = time.perf_counter() - start

print(f'project-only baseline elapsed: {local_elapsed:.2f} s')
print(f'baseline + groupby(region).aggregate elapsed: {grouped_elapsed:.2f} s')
print(f'aggregation / baseline ratio: {grouped_elapsed / local_elapsed:.2f}x')

Parquet dataset sampling: 100%|██████████| 2.00/2.00 [00:00<00:00, 106 file/s]
2026-05-14 13:10:47,215	INFO parquet_datasource.py:1079 -- Estimated parquet encoding ratio is 14.810.
2026-05-14 13:10:47,216	INFO parquet_datasource.py:1139 -- Estimated parquet reader batch size at 65218 rows
2026-05-14 13:10:47,221	INFO logging.py:392 -- Registered dataset logger for dataset dataset_17_0
2026-05-14 13:10:47,225	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_17_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:47,226	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_17_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet]
2026-05-14 13:10:47,246	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_17_0 =======
2026-05-14 13:10:47,249	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:47,250	INFO logging_progress.py:227 -- Active & requested resources: 0/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:47,251	INFO logging_progress.py:181 --
2026-05-14 13:10:47,251	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:47,252	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:47,253	INFO logging_progress.py:192 -- =============================================
2026-05-14 13:10:47,286	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_17_0 execution finished in 0.06 seconds
Parquet dataset sampling: 100%|██████████| 2.00/2.00 [00:00<00:00, 75.3 file/s]
2026-05-14 13:10:47,357	INFO parquet_datasource.py:1079 -- Estimated parquet encoding ratio is 14.810.
2026-05-14 13:10:47,359	INFO parquet_datasource.py:1139 -- Estimated parquet reader batch size at 65218 rows
2026-05-14 13:10:47,366	INFO logging.py:392 -- Registered dataset logger for dataset dataset_23_0
2026-05-14 13:10:47,369	INFO hash_aggregate.py:161 -- Estimated memory requirement for aggregating aggregator (partitions=8, aggregators=8, dataset (estimate)=0.1GiB): shuffle=14.7MiB, output=14.7MiB, total=29.4MiB,
2026-05-14 13:10:47,373	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_23_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:47,374	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_23_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> HashAggregateOperator[HashAggregate(key_columns=('region',), num_partitions=8)]
2026-05-14 13:10:47,417	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_23_0 =======
2026-05-14 13:10:47,419	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:47,420	INFO logging_progress.py:227 -- Active & requested resources: 0.08/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:47,421	INFO logging_progress.py:181 --
2026-05-14 13:10:47,422	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:47,423	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:47,424	INFO logging_progress.py:231 -- HashAggregate(key_columns=('region',), num_partitions=8): 0/1
2026-05-14 13:10:47,425	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.1 CPU, 0.0B object store
2026-05-14 13:10:47,425	INFO logging_progress.py:231 --     - Shuffle: 0/1
2026-05-14 13:10:47,426	INFO logging_progress.py:231 --     - Aggregation: 0/1
2026-05-14 13:10:47,427	INFO logging_progress.py:192 -- =============================================
2026-05-14 13:10:50,655	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_23_0 execution finished in 3.28 seconds

project-only baseline elapsed: 0.11 s
baseline + groupby(region).aggregate elapsed: 3.48 s
aggregation / baseline ratio: 32.82x

In [30]:
print(region_summary.stats())
display(region_summary.to_pandas().sort_values('region').reset_index(drop=True))

Operator 1 ReadParquet: 8 tasks executed, 8 blocks produced in 0.08s
* Remote wall time: 3.9ms min, 6.8ms max, 4.61ms mean, 36.89ms total
* Remote cpu time: 0.0us min, 15.62ms max, 3.91ms mean, 31.25ms total
* UDF time: 0us min, 0us max, 0.0us mean, 0us total
* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
* Output num rows per block: 7500 min, 7500 max, 7500 mean, 60000 total
* Output size bytes per block: 112629 min, 112997 max, 112847 mean, 902776 total
* Output rows per task: 7500 min, 7500 max, 7500 mean, 8 tasks used
* Tasks per node: 8 min, 8 max, 8 mean; 1 nodes used
* Operator throughput:
	* Total input num rows: 0 rows
	* Total output num rows: 60000 rows
	* Ray Data throughput: 745194.4274263884 rows/s
	* Estimated single task throughput: 1626302.7375113752 rows/s

Operator 2 HashAggregate(key_columns=('region',), num_partitions=8): executed in 3.28s

	Suboperator 0 HashAggregate(key_columns=('region',), num_partitions=8)HashAggregate(key_columns=('region',), num_partitions=8)_shuffle: 1 tasks executed, 8 blocks produced
	* Remote wall time: 2.76s min, 3.09s max, 2.9s mean, 23.22s total
	* Remote cpu time: 156.25ms min, 250.0ms max, 189.45ms mean, 1.52s total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 5 min, 5 max, 5 mean, 40 total
	* Output size bytes per block: 216 min, 216 max, 216 mean, 1728 total
	* Output rows per task: 40 min, 40 max, 40 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 60000 rows
		* Total output num rows: 40 rows
		* Ray Data throughput: 12.955399288976906 rows/s
		* Estimated single task throughput: 1.7223481588845762 rows/s

	Suboperator 1 HashAggregate(key_columns=('region',), num_partitions=8)HashAggregate(key_columns=('region',), num_partitions=8)_finalize: 1 tasks executed, 8 blocks produced
	* Remote wall time: 324.8us min, 14.01ms max, 6.71ms mean, 53.65ms total
	* Remote cpu time: 0.0us min, 31.25ms max, 7.81ms mean, 62.5ms total
	* UDF time: 0us min, 0us max, 0.0us mean, 0us total
	* Peak heap memory usage (MiB): 0.0 min, 0.0 max, 0 mean
	* Output num rows per block: 0 min, 2 max, 0 mean, 5 total
	* Output size bytes per block: 0 min, 64 max, 19 mean, 156 total
	* Output rows per task: 5 min, 5 max, 5 mean, 1 tasks used
	* Tasks per node: 1 min, 1 max, 1 mean; 1 nodes used
	* Operator throughput:
		* Total input num rows: 40 rows
		* Total output num rows: 5 rows
		* Ray Data throughput: 258.93587709535205 rows/s
		* Estimated single task throughput: 93.19108646431964 rows/s

Dataset throughput:
	* Ray Data throughput: 1.5811576603973527 rows/s

  region  events  mean_latency_ms  total_spend_usd
0   APAC   13149        94.100768     26101.919975
1     EU   16145        94.161103     35175.570000
2  LATAM    6135        93.943113     14611.759993
3    MEA    3065        94.057096      7100.019988
4     NA   21506        94.347624     47669.920018

#### Reading the `stats()` output

- Did projection pushdown work? Check `ReadParquet` -> `Output size bytes`. It should be small because `payload_blob` is not read here.
- Where is the time? Compare `ReadParquet` time with `HashAggregate(...): executed in ...`.
- Which part of aggregation dominates? Compare the `_shuffle` _(communication)_ suboperator with `_finalize` _(local reduction)_.

**Conclusion**: projection is local; aggregation by key is global. `groupby(...).aggregate(...)` is expensive because Ray cannot finish the job block by block in isolation.

## 3. Custom aggregators

Building a custom aggregator exposes the same shuffle/reduction pattern used by the built-in aggregators:

1. Compute a small partial state inside each block.
2. Shuffle/repartition those partial states by group key.
3. Reduce the matching partial states locally.
4. Finalize the reduced state into the answer you want.

Input: rows with `region` and `spend_usd`.

Output: one row per `region` with `paid_event_rate`, the share of events where `spend_usd > 0`.

The implementation follows the four steps above:

1. `aggregate_block` scans one local chunk for a group and returns `[paid_events, total_events]`.
2. Ray shuffles those partial states so matching `region` keys are collocated.
3. `combine` locally reduces matching partial states by adding the two counts. It may be called multiple times as Ray merges partial accumulators for each key.
4. `finalize` turns the reduced `[paid_events, total_events]` state into `paid_events / total_events`.

![aggregator.png](images/aggregator.png)

In [31]:
class PaidEventRate(AggregateFnV2):
    def __init__(self):
        super().__init__(
            'paid_event_rate',
            on='spend_usd',
            ignore_nulls=False,
            zero_factory=lambda: [0, 0],
        )

    def aggregate_block(self, block):
        pdf = BlockAccessor.for_block(block).to_pandas()
        paid_event_mask = pdf['spend_usd'] > 0
        paid_events = int(paid_event_mask.sum())
        total_events = len(pdf)
        return [paid_events, total_events]

    def combine(self, current_accumulator, new_accumulator):
        current_paid_events, current_total_events = current_accumulator
        new_paid_events, new_total_events = new_accumulator

        return [
            current_paid_events + new_paid_events,
            current_total_events + new_total_events,
        ]

    def finalize(self, accumulator):
        paid_events, total_events = accumulator
        return paid_events / total_events


paid_rate_by_region = (
    events_ds
    .select_columns(['region', 'spend_usd'])
    .groupby('region')
    .aggregate(PaidEventRate())
)

display(paid_rate_by_region.to_pandas().sort_values('region').reset_index(drop=True))

2026-05-14 13:10:50,880	INFO logging.py:392 -- Registered dataset logger for dataset dataset_27_0
2026-05-14 13:10:50,884	INFO hash_aggregate.py:161 -- Estimated memory requirement for aggregating aggregator (partitions=8, aggregators=8, dataset (estimate)=0.1GiB): shuffle=14.7MiB, output=14.7MiB, total=29.4MiB,
2026-05-14 13:10:50,891	INFO streaming_executor.py:182 -- Starting execution of Dataset dataset_27_0. Full logs are in C:\Users\alter\AppData\Local\Temp\ray\session_2026-05-14_13-10-34_400172_462120\logs\ray-data
2026-05-14 13:10:50,892	INFO streaming_executor.py:183 -- Execution plan of Dataset dataset_27_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadParquet] -> HashAggregateOperator[HashAggregate(key_columns=('region',), num_partitions=8)]
2026-05-14 13:10:50,926	INFO logging_progress.py:174 -- ======= Running Dataset: dataset_27_0 =======
2026-05-14 13:10:50,929	INFO logging_progress.py:225 -- Total Progress: 0/?
2026-05-14 13:10:50,929	INFO logging_progress.py:227 -- Active & requested resources: 0.08/12 CPU, 0.0B/2.3GiB object store
2026-05-14 13:10:50,930	INFO logging_progress.py:181 --
2026-05-14 13:10:50,931	INFO logging_progress.py:231 -- ReadParquet: 0/1
2026-05-14 13:10:50,932	INFO logging_progress.py:233 --   Tasks: 1; Actors: 0; Queued blocks: 7 (0.0B); Resources: 1.0 CPU, 384.0MiB object store
2026-05-14 13:10:50,933	INFO logging_progress.py:231 -- HashAggregate(key_columns=('region',), num_partitions=8): 0/1
2026-05-14 13:10:50,933	INFO logging_progress.py:233 --   Tasks: 0; Actors: 0; Queued blocks: 0 (0.0B); Resources: 0.1 CPU, 0.0B object store
2026-05-14 13:10:50,934	INFO logging_progress.py:231 --     - Shuffle: 0/1
2026-05-14 13:10:50,935	INFO logging_progress.py:231 --     - Aggregation: 0/1
2026-05-14 13:10:50,936	INFO logging_progress.py:192 -- =============================================
2026-05-14 13:10:53,803	INFO streaming_executor.py:300 -- ✔️  Dataset dataset_27_0 execution finished in 2.91 seconds

  region  paid_event_rate
0   APAC         0.067914
1     EU         0.069805
2  LATAM         0.079707
3    MEA         0.072104
4     NA         0.070817

## 4. Summary

This notebook only covered a high-level slice of Ray Data. The full API is broader, and it also works beyond tabular ETL workloads, including text, images, tensors, and batch inference pipelines.

The key ideas to keep are:

- Think in blocks, not individual rows.
- Ray Data builds and optimizes a lazy plan, so adjacent block-local operations may be fused or pushed earlier when it is safe. Still, the optimizer is limited so writing the plan in the most efficient order is healthy.
- Prefer block-local narrowing steps like `filter`, `select_columns`, and many `map_batches` transforms before all-to-all work.
- Methods like `sort()` and `groupby(...).aggregate(...)` are lazy, but when executed they become expensive global operations.
- `materialize()`, `show()`, `sum()`, `to_pandas()`, and often `count()` are the kinds of calls that force execution.
- If a later stage only needs a few columns, project early before the global op.
- Bring data back to pandas only when the result is genuinely small.

For a broader tour of the API, see the [Ray Data docs](https://docs.ray.io/en/latest/data/key-concepts.html) and the [Aggregating Data guide](https://docs.ray.io/en/latest/data/aggregating-data.html).